In [4]:
import numpy as np

float64
[1 3 8]
int64


In [1]:
python_list = [1,2,3,4,5]
print(python_list)

[1, 2, 3, 4, 5]


In [5]:

numpy_array = np.array([1,2,3,4,5])
print(numpy_array)

[1 2 3 4 5]


In [6]:
#1-D array
arr_1D = np.array([10,20,30,40,50])
print(arr_1D)
print(type(arr_1D))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [7]:
#2D- Array  #matrix
arr_2D= np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(arr_2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
#multi_D array
mul_arr = np.array([[2,4,6],
                   [8,10,12]])
print(mul_arr)

[[ 2  4  6]
 [ 8 10 12]]


In [9]:
#creating arrays from python list
arr = np.array([1,2,3,4]) 
print(arr)

[1 2 3 4]


In [ ]:
#changing data type
arr = np.array([1.2, 3.5, 8.6])
print(arr.dtype)
int_arr = arr.astype(int) 
print(int_arr)
print(int_arr.dtype)

In [ ]:
#creating arrays with default values
arr = np.zeros(shape=5) #prints 0 at all indices
print(arr)

arr = np.ones(shape=5) #print 1 at all indices
print(arr) 

arr = np.full((1,2),9) #prints 9(any specific num) (1,2 means 1 row and 2 columns)
print (arr)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[9 9]]


In [11]:
#creating sequence of nums in numpy
arr = np.arange(1,6,1)  #(start, stop, step) step --> means add by how much
print(arr)

[1 2 3 4 5]


In [14]:
#creating idientity matrix
arr = np.eye(3)  #3 means num of rows and colmns
print ( arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#how to check shape (structure) of an array
arr_2D = np.array([[1,2,3],
                  [4,5,6]])
print(arr_2D.shape)  #result will be no. of rows, colmns

(2, 3)


In [16]:
#size of an array
arr_2D= np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])
print(arr_2D.size)

10


In [17]:
#num of dimensions in an array
arr = np.array([[1,2,3],[4,5,6],[7,8,9], [12,13,14]])
print(arr.ndim)

2


In [19]:
#type of elements in an array
arr = np.array([[1,2],[3,4],[20,30]])
print(arr.dtype)

int64


In [18]:
#changing data type
arr = np.array([1.2, 3.5, 8.6])
print(arr.dtype)
int_arr = arr.astype(int) 
print(int_arr)
print(int_arr.dtype)

float64
[1 3 8]
int64
